server:
  port: 8082

jwt:
  secret-key: '{cipher}cb5105cee42d766062024b0a05cbaf78c66a76a3a272fe5d4fdf2b91e1769fa4b1e827f6bc05823da7fb224dc3b021638314288c9920b671ac21095d3b539f150af18c32c2c057f0da83b27b16a2e8af7ca0ce8dd35cebcc0934a04d99f78023c3a95dc17cf6c080ee7705810d6e5902'

spring:
  application:
    name: post-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smilegatedevcamp?Unicode=true&characterEncoding=utf8
    username: root
    password: 112233
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

resilience4j:
  circuitbreaker:
    failure-rate-threshold: 10   # 실패 10% 이상 시 서킷 오픈
    slow-call-duration-threshold: 500   # 500ms 이상 소요 시 실패로 간주
    slow-call-rate-threshold: 10   # slowCallDurationThreshold 초과 비율이 10% 이상 시 서킷 오픈
    wait-duration-in-open-state: 30000   # OPEN -> HALF-OPEN 전환 전 기다리는 시간
    minimum-number-of-calls: 50   # 집계에 필요한 최소 호출 수
    sliding-window-size: 100   # 서킷 CLOSE 상태에서 N회 호출 도달 시 failureRateThreshold 실패 비율 계산
    permitted-number-of-calls-in-half-open-state: 30   # HALFOPEN -> CLOSE or OPEN 으로 판단하기 위해 호출 횟수
  retry:
    wait-duration: 100   # 재시도 사이 간격
    max-attempts: 2   # 재시도 횟수(최초 호출 포함)

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

  health:
    circuitbreakers:
      enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
